image: ros:melodic-robot

before_script:
  - git clone https://gitlab.com/itu-auv/electronics/mainboard-firmware.git
  - apt-get update > /dev/null

PlatformIO Build:
  stage: build
  script:
    - apt-get install -y python-pip
    - pip install -U platformio
    - cd mainboard-firmware
    - platformio run
 
Catkin Build: 
  stage: build
  script:
    - mkdir -p catkin_ws/src
    - mv mainboard-firmware/ catkin_ws/src/
    - cd catkin_ws
    - apt-get install -y python-catkin-tools > /dev/null
    - apt-get install -y ros-melodic-rosserial > /dev/null
    - catkin build --force-color
    
